ai:
    platform:
        # Inference Platform configuration
        # see https://github.com/symfony/ai/tree/main/src/platform#platform-bridges

    agent:
        # Agent configuration
        # see https://symfony.com/doc/current/ai/bundles/ai-bundle.html

        resume_drafter.ollama:
            platform: ai.platform.ollama
            model: '%resume_drafter.ollama.model%'
            prompt: '%prompts.resume_drafter%'
        resume_drafter.gemini:
            platform: ai.platform.gemini
            model: '%resume_drafter.gemini.model%'
            prompt: '%prompts.resume_drafter%'

        resume_fact_checker.ollama:
            platform: ai.platform.ollama
            model: '%resume_fact_checker.ollama.model%'
            prompt: '%prompts.resume_fact_checker%'
        resume_fact_checker.gemini:
            platform: ai.platform.gemini
            model: '%resume_fact_checker.gemini.model%'
            prompt: '%prompts.resume_fact_checker%'

        #

        archetype_selector:
            platform: ai.platform.ollama
            model: archetype-selector
            prompt: '%prompts.archetype_selector%'
            tools:
                enabled: true
                services:
                    - service: App\AI\Agent\Toolbox\ArchetypeDirectoryTool

        resume_drafter:
            platform: ai.platform.ollama
            model: resume-drafter
            prompt: '%prompts.resume_drafter%'

        resume_smell_checker:
            platform: ai.platform.ollama
            model: resume-smell-checker
            prompt: '%prompts.resume_smell_checker%'

        resume_reviser:
            platform: ai.platform.ollama
            model: resume-reviser
            prompt: '%prompts.resume_reviser%'

        resume_finalizer:
            platform: ai.platform.ollama
            model: resume-finalizer
            prompt: '%prompts.resume_finalizer%'

    store:
        # Store configuration

        # chromadb:
        #    default:
        #        client: 'client.service.id'
        #        collection: 'my_collection'
