ai:
    platform:
        # Inference Platform configuration
        # see https://github.com/symfony/ai/tree/main/src/platform#platform-bridges

        ollama:
            http_client: ollama.client

    agent:
        # Agent configuration
        # see https://symfony.com/doc/current/ai/bundles/ai-bundle.html

        resume_drafter:
            platform: ai.platform.ollama
            model: resume-drafter
            prompt: '%prompts.resume_drafter%'

    store:
        # Store configuration

        # chromadb:
        #    default:
        #        client: 'client.service.id'
        #        collection: 'my_collection'
