# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    #
    # Content Base Paths
    #

    env(CONTENT_PATH): '%kernel.project_dir%/content'
    content_path: '%env(resolve:CONTENT_PATH)%'

    env(ARCHETYPES_PATH): '%content_path%/archetypes'
    archetypes_path: '%env(resolve:ARCHETYPES_PATH)%'

    env(PII_PATH): '%content_path%/pii'
    pii_path: '%env(resolve:PII_PATH)%'

    env(PROMPTS_PATH): '%content_path%/prompts'
    prompts_path: '%env(resolve:PROMPTS_PATH)%'

    #
    # Content
    #

    content_not_found: 'Not Found'

    # Personal Info
    env(SAMPLE_PERSONAL_INFO_PATH): '%pii_path%/personal_info.sample.md'
    env(PERSONAL_INFO_PATH): '%pii_path%/personal_info.md'
    pii.sample_personal_info: '%env(default:content_not_found:file:resolve:SAMPLE_PERSONAL_INFO_PATH)%'
    pii.personal_info: '%env(default:pii.sample_personal_info:file:resolve:PERSONAL_INFO_PATH)%'

    # Education History
    env(SAMPLE_EDUCATION_HISTORY_PATH): '%pii_path%/education_history.sample.md'
    env(EDUCATION_HISTORY_PATH): '%pii_path%/education_history.md'
    pii.sample_education_history: '%env(default:content_not_found:file:resolve:SAMPLE_EDUCATION_HISTORY_PATH)%'
    pii.education_history: '%env(default:pii.sample_education_history:file:resolve:EDUCATION_HISTORY_PATH)%'

    # Work History
    env(SAMPLE_WORK_HISTORY_PATH): '%pii_path%/work_history.sample.md'
    env(WORK_HISTORY_PATH): '%pii_path%/work_history.md'
    pii.sample_work_history: '%env(default:content_not_found:file:resolve:SAMPLE_WORK_HISTORY_PATH)%'
    pii.work_history: '%env(default:pii.sample_work_history:file:resolve:WORK_HISTORY_PATH)%'

    # Extras
    env(SAMPLE_EXTRAS_PATH): '%pii_path%/extras.sample.md'
    env(EXTRAS_PATH): '%pii_path%/extras.md'
    pii.sample_extras: '%env(default:content_not_found:file:resolve:SAMPLE_EXTRAS_PATH)%'
    pii.extras: '%env(default:pii.sample_extras:file:resolve:EXTRAS_PATH)%'

    # Resume Archetype Selector Prompt
    env(RESUME_ARCHETYPE_SELECTOR_PROMPT_PATH): '%prompts_path%/resume_archetype_selector.md'
    prompts.resume_archetype_selector: '%env(resolve:default:content_not_found:file:resolve:RESUME_ARCHETYPE_SELECTOR_PROMPT_PATH)%'

    # Resume Drafter Prompt
    env(RESUME_DRAFTER_PROMPT_PATH): '%prompts_path%/resume_drafter.md'
    prompts.resume_drafter: '%env(resolve:default:content_not_found:file:resolve:RESUME_DRAFTER_PROMPT_PATH)%'

    # Resume Fact-Checker Prompt
    env(RESUME_FACT_CHECKER_PROMPT_PATH): '%prompts_path%/resume_fact_checker.md'
    prompts.resume_fact_checker: '%env(resolve:default:content_not_found:file:resolve:RESUME_FACT_CHECKER_PROMPT_PATH)%'

    # Resume Job-Alignment-Checker Prompt
    env(RESUME_JOB_ALIGNMENT_CHECKER_PROMPT_PATH): '%prompts_path%/resume_job_alignment_checker.md'
    prompts.resume_job_alignment_checker: '%env(resolve:default:content_not_found:file:resolve:RESUME_JOB_ALIGNMENT_CHECKER_PROMPT_PATH)%'

    # Resume Editor Prompt
    env(RESUME_EDITOR_PROMPT_PATH): '%prompts_path%/resume_editor.md'
    prompts.resume_editor: '%env(resolve:default:content_not_found:file:resolve:RESUME_EDITOR_PROMPT_PATH)%'

    #
    # Models
    #

    # Resume Archetype Selector Models
    resume_archetype_selector.ollama.model: '%env(OLLAMA_AGENT_RESUME_ARCHETYPE_SELECTOR_MODEL)%'
    resume_archetype_selector.ollama.model_params: '%env(json:OLLAMA_AGENT_RESUME_ARCHETYPE_SELECTOR_MODEL_PARAMS)%'
    resume_archetype_selector.gemini.model: '%env(GEMINI_AGENT_RESUME_ARCHETYPE_SELECTOR_MODEL)%'
    resume_archetype_selector.gemini.model_params: '%env(json:GEMINI_AGENT_RESUME_ARCHETYPE_SELECTOR_MODEL_PARAMS)%'

    # Resume Drafter Models
    resume_drafter.ollama.model: '%env(OLLAMA_AGENT_RESUME_DRAFTER_MODEL)%'
    resume_drafter.ollama.model_params: '%env(json:OLLAMA_AGENT_RESUME_DRAFTER_MODEL_PARAMS)%'
    resume_drafter.gemini.model: '%env(GEMINI_AGENT_RESUME_DRAFTER_MODEL)%'
    resume_drafter.gemini.model_params: '%env(json:GEMINI_AGENT_RESUME_DRAFTER_MODEL_PARAMS)%'

    # Resume Fact-Checker Models
    resume_fact_checker.ollama.model: '%env(OLLAMA_AGENT_RESUME_FACT_CHECKER_MODEL)%'
    resume_fact_checker.ollama.model_params: '%env(json:OLLAMA_AGENT_RESUME_FACT_CHECKER_MODEL_PARAMS)%'
    resume_fact_checker.gemini.model: '%env(GEMINI_AGENT_RESUME_FACT_CHECKER_MODEL)%'
    resume_fact_checker.gemini.model_params: '%env(json:GEMINI_AGENT_RESUME_FACT_CHECKER_MODEL_PARAMS)%'

    # Resume Job-Alignment-Checker Models
    resume_job_alignment_checker.ollama.model: '%env(OLLAMA_AGENT_RESUME_JOB_ALIGNMENT_CHECKER_MODEL)%'
    resume_job_alignment_checker.ollama.model_params: '%env(json:OLLAMA_AGENT_RESUME_JOB_ALIGNMENT_CHECKER_MODEL_PARAMS)%'
    resume_job_alignment_checker.gemini.model: '%env(GEMINI_AGENT_RESUME_JOB_ALIGNMENT_CHECKER_MODEL)%'
    resume_job_alignment_checker.gemini.model_params: '%env(json:GEMINI_AGENT_RESUME_JOB_ALIGNMENT_CHECKER_MODEL_PARAMS)%'

    # Resume Editor Models
    resume_editor.ollama.model: '%env(OLLAMA_AGENT_RESUME_EDITOR_MODEL)%'
    resume_editor.ollama.model_params: '%env(json:OLLAMA_AGENT_RESUME_EDITOR_MODEL_PARAMS)%'
    resume_editor.gemini.model: '%env(GEMINI_AGENT_RESUME_EDITOR_MODEL)%'
    resume_editor.gemini.model_params: '%env(json:GEMINI_AGENT_RESUME_EDITOR_MODEL_PARAMS)%'

    #

    #env(SAMPLE_PERSONAL_INFO_PATH): '%content_path%/pii/personal_info.sample.md'
    #env(PERSONAL_INFO_PATH): '%content_path%/pii/personal_info.md'
    #pii.sample_personal_info: '%env(default:content_not_found:file:SAMPLE_PERSONAL_INFO_PATH)%'
    #pii.personal_info: '%env(default:pii.sample_personal_info:file:PERSONAL_INFO_PATH)%'

    #env(SAMPLE_EDUCATION_HISTORY_PATH): '%content_path%/pii/education_history.sample.md'
    #env(EDUCATION_HISTORY_PATH): '%content_path%/pii/education_history.md'
    #pii.sample_education_history: '%env(default:content_not_found:file:SAMPLE_EDUCATION_HISTORY_PATH)%'
    #pii.education_history: '%env(default:pii.sample_education_history:file:EDUCATION_HISTORY_PATH)%'

    #env(SAMPLE_WORK_HISTORY_PATH): '%content_path%/pii/work_history.sample.md'
    #env(WORK_HISTORY_PATH): '%content_path%/pii/work_history.md'
    #pii.sample_work_history: '%env(default:content_not_found:file:SAMPLE_WORK_HISTORY_PATH)%'
    #pii.work_history: '%env(default:pii.sample_work_history:file:WORK_HISTORY_PATH)%'

    #env(SAMPLE_EXTRAS_PATH): '%content_path%/pii/extras.sample.md'
    #env(EXTRAS_PATH): '%content_path%/pii/extras.md'
    #pii.sample_extras: '%env(default:content_not_found:file:SAMPLE_EXTRAS_PATH)%'
    #pii.extras: '%env(default:pii.sample_extras:file:EXTRAS_PATH)%'

    env(ARCHETYPE_SELECTOR_PROMPT_PATH): '%content_path%/prompts/archetype_selector.md'
    prompts.archetype_selector: '%env(resolve:default:content_not_found:file:ARCHETYPE_SELECTOR_PROMPT_PATH)%'

    #env(RESUME_DRAFTER_PROMPT_PATH): '%content_path%/prompts/resume_drafter.md'
    #prompts.resume_drafter: '%env(resolve:default:content_not_found:file:RESUME_DRAFTER_PROMPT_PATH)%'

    #models.resume_drafter: '%env(AGENT_RESUME_DRAFTER_MODEL)%'
    #model_params.resume_drafter: '%env(json:AGENT_RESUME_DRAFTER_MODEL_PARAMS)%'

    env(RESUME_SMELL_CHECKER_PROMPT_PATH): '%content_path%/prompts/resume_smell_checker.md'
    prompts.resume_smell_checker: '%env(resolve:default:content_not_found:file:RESUME_SMELL_CHECKER_PROMPT_PATH)%'

    env(RESUME_REVISER_PROMPT_PATH): '%content_path%/prompts/resume_reviser.md'
    prompts.resume_reviser: '%env(resolve:default:content_not_found:file:RESUME_REVISER_PROMPT_PATH)%'

    env(RESUME_FINALIZER_PROMPT_PATH): '%content_path%/prompts/resume_finalizer.md'
    prompts.resume_finalizer: '%env(resolve:default:content_not_found:file:RESUME_FINALIZER_PROMPT_PATH)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
